GET http://localhost:5000/api/todos

###

POST http://localhost:5000/api/todo/new
Content-Type: application/json

{
    "title": "Otra tarea"
}

###

GET http://localhost:5000/api/todo/toggleDelete/63cefbc386e73829969c6d8d

###

GET http://localhost:5000/api/todo/toggleStatus/63c9d8596640bc8718b631f8

###

PUT http://localhost:5000/api/todo/editTodo/63c9d8566640bc8718b631f4
Content-Type: application/json

{
    "title": "Tarea de prueba editada"
}